export const ADD_SECURITY = 'ADD_SECURITY';
export const EDIT_SECURITY = 'EDIT_SECURITY';
export const DELETE_SECURITY = 'DELETE_SECURITY';

export const OPEN_ADD_MODAL = 'OPEN_ADD_MODAL'
export const CLOSE_ADD_MODAL = 'CLOSE_ADD_MODAL'

export const OPEN_EDIT_MODAL = 'OPEN_EDIT_MODAL'
export const CLOSE_EDIT_MODAL = 'CLOSE_EDIT_MODAL'

export const OPEN_PRICES_MODAL = 'OPEN_PRICES_MODAL'
export const CLOSE_PRICES_MODAL = 'CLOSE_PRICES_MODAL'

export const EDIT_PRICE = 'EDIT_PRICE';
export const DELETE_PRICE = 'DELETE_PRICE';
export const ADD_PRICE = 'ADD_PRICE';
